name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install

      - name: Set npm registry and authentication
        run: |
          npm config set registry "https://registry.npmjs.org"
          echo "//registry.npmjs.org/:_authToken=\$TOKEN" > ~/.npmrc

      - name: Publish to npm
        run: |
          npm publish || echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1)
