name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Install npm on bun"
        run: |
          bun install npm

      - name: Set npm registry and authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${TOKEN}" > ~/.npmrc

      - name: Publish to npm
        run: |
          bun install
          bun run build 
          bun run publish || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
