name: Publish Package to npmjs

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      otp:
        description: Enter OTP
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>

      - name: "Install npm on bun"
        run: |
          bun install npm

      - name: Set npm registry and authentication
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ ${#NPM_TOKEN} -eq 0 ]; then
            echo "NPM_TOKEN is empty. Exiting."
            exit 1
          fi
          bun run npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Publish to npm
        run: |
          OTP=${{ github.event.inputs.otp }}
          bun run npm publish --access public --verbose --otp $OTP || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)

      - name: Install and build
        run: |
          bun install
          bun run build

      - name: List all files
        run: |
          find . -type f -not -path "./node_modules/*" -not -path "./.git/*"

      - name: Publish to npm
        run: |
          bun run npm publish --access public --verbose || (echo "Error publishing to npm, see the error log below:" && cat $(ls -1t /home/runner/.npm/_logs/*-debug-0.log | head -n 1) && exit 1)
