name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>

      # run any `bun` or `bunx` command
      - name: Install and Build
        run: |
          bun run npm config set registry "https://registry.npmjs.org"
          bun run npm config set _authToken=${{ secrets.NPM_TOKEN }}
          bun run npm publish
